# Generated by Django 2.2.4 on 2019-09-16 09:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='file_name',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\dboya\\PycharmProjects\\pd-diplom\\orders\\storage'), upload_to='', verbose_name=''),
        ),
    ]
